services:
  server:
    build: .
    container_name: curia-express
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
